cmake_minimum_required(VERSION 3.15)
project(DNSCascade CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
add_compile_options(-Wall -Wextra)

add_subdirectory(common)
add_subdirectory(server)
add_subdirectory(root)
add_subdirectory(tld)
add_subdirectory(authoritative)
add_subdirectory(client)
add_subdirectory(resolver)